### ISSUE TITLE
Computation complexity of different models.

### ISSUE THREAD

**Issue by godlin-sjtu** [nobodyplayer1/VM-UNetV2#1]
To whom it may concern,

Nice job! And I have a small question about the results of Table 3 in your paper.  It shows that the Flops and Params of VM-UnetV2 are lower than those of VM-Unet（I guess it refers to 'VM-UNet: Vision Mamba UNet for Medical Image Segmentation').  However, in my view, this paper seems to add an extra SDI module to VM-Unet, and why have these two metrics **decreased**?

I am looking forward to your response, many thanks.

**Comment by nobodyplayer1** [comment]
Thanks for the question, it's a good one. Here is the answer: the parameter amount is smaller because we are not directly applying the decoder module in VM-Unet.As you can see in the open source code, our four layers output is directly from the encoder part of the four layers through an SDI module.（If there is still any doubt about this we will upload a file again in the near future to clarify this matter, in the meantime you can check our code in the file **models/vmunet/vmunet_v2.py**）

**Comment by godlin-sjtu** [comment]
Thanks for your answer, I have checked the paper and code again, and my issue is resolved.
